"use client";
import { useState } from "react";
import Link from "next/link";
import offerData from "../offer-data.json";
import { QuoteDialog } from "../quote-dialog";
import { OfferFAQ } from "../offer-details";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
export function BioProductPage() {
 const [solution, setSolution] = useState<string | null>(null);
 return <main className="bio-product-page offer-bio-page">
  <nav className="bio-nav shell"><Link className="brand" href="/"><span className="brand-mark">S</span><span>suapage<span className="brand-dot">.</span></span></Link><Link className="bio-back" href="/#pacotes">← ver os projetos</Link><button className="nav-cta" onClick={() => setSolution("Landing de Serviço")}>Quero site + Bio ↗</button></nav>
  <section className="bio-hero-product shell"><div className="bio-product-copy"><div className="kicker"><span className="pulse"/> um complemento ao seu projeto</div><h1>Seu site e sua Bio.<br/><em>A mesma identidade.</em></h1><p>Do Instagram ao seu site, uma apresentação consistente. Criamos seu link na bio com as mesmas cores, tipografia e direção visual do projeto principal.</p><div className="bio-product-actions"><button className="button button-primary" onClick={() => setSolution("Landing de Serviço")}>Quero meu site + Bio <span>↗</span></button><a className="text-link" href="#combo">Ver os valores ↓</a></div><div className="bio-product-proof"><span>+ R$ 490 no projeto</span><span>·</span><span>mesmo domínio</span><span>·</span><span>tudo pronto</span></div></div><div className="bio-demo-wrap"><div className="bio-demo-shadow"/><div className="bio-demo"><div className="demo-tape"/><div className="demo-avatar">S</div><b>seunegocio</b><span className="demo-description">Seu trabalho, bem apresentado.</span><div className="demo-chip">+ sua apresentação</div><div className="demo-link">Conheça meus serviços <span>↗</span></div><div className="demo-link">Veja meu trabalho <span>↗</span></div><div className="demo-link dark">Fale comigo no WhatsApp <span>↗</span></div><div className="demo-social">site · contato · redes</div><small>Exemplo ilustrativo · <strong>suapage.</strong></small></div></div></section>
  <section className="bio-product-section" id="como-funciona"><div className="shell"><div className="overline">cada página tem seu papel</div><h2>O site explica.<br/><em>A Bio conecta.</em></h2><div className="bio-benefits"><div><span>01</span><h3>Seu site principal</h3><p>Apresenta seus serviços ou produto em profundidade, responde dúvidas e conduz até o contato ou a compra.</p></div><div><span>02</span><h3>Sua Bio personalizada</h3><p>Organiza os caminhos de quem chega pelo Instagram: site, serviços, portfólio, WhatsApp e outras redes.</p></div><div><span>03</span><h3>Uma entrega completa</h3><p>Nós escrevemos, desenhamos e publicamos as duas páginas. Você valida; futuras alterações são feitas pela Suapage.</p></div></div></div></section>
  <section className="bio-scope shell"><div className="overline">o que entra na Bio</div><h2>Pequena no formato.<br/><em>Inteira na sua identidade.</em></h2><ul><li>1 página adicional com até 6 blocos e até 10 links ou botões no total.</li><li>Foto ou logo, apresentação breve, destaques de serviços, links, redes e contato.</li><li>Cores, tipografia e direção visual alinhadas ao site contratado.</li><li>Publicação no mesmo domínio, em um endereço como /bio.</li><li>Até 2 rodadas de revisão do conjunto site + Bio e 30 dias de pequenos ajustes após a entrega.</li></ul><p className="offer-caption">O combo usa uma só hospedagem de R$ 49/mês. Domínio comprado e renovado pelo cliente. Não inclui editor próprio, chatbot, carrinho ou sistema de agendamento; podemos incluir links para serviços externos já contratados.</p></section>
  <section className="bio-product-pricing shell" id="combo"><div><div className="overline">escolha seu projeto, acrescente sua Bio</div><h2>Dois destinos.<br/><em>Uma só marca.</em></h2></div><div className="offer-bio-plans">{Object.values(offerData).map(pack => <article key={pack.id}><span className="overline">site + Bio personalizada</span><h3>{pack.name}</h3><p>{pack.limit}, mais sua Bio.</p><small>a partir de</small><br/><strong>{money(pack.price + 490)}</strong><p>{money(pack.price)} pelo projeto + R$ 490 pela Bio.<br/>Hospedagem: R$ 49/mês. Domínio à parte.</p><button className="button button-primary" onClick={() => setSolution(pack.name)}>Quero este combo ↗</button></article>)}</div></section>
  <OfferFAQ />
  <footer className="footer shell"><Link className="brand" href="/"><span className="brand-mark">S</span><span>suapage.</span></Link><span>sites & experiências digitais</span><span>© 2026 Suapage</span></footer>
  {solution && <QuoteDialog initialSolution={solution} includeBio onClose={() => setSolution(null)} />}
 </main>;
}
export default BioProductPage;
