export function OfferConditions() {
  return <section className="offer-delivery shell" id="entrega">
    <div className="overline">um combinado claro, desde o começo</div>
    <h2>Tudo pronto para validar.<br /><em>Sem começar do zero sozinho.</em></h2>
    <div className="delivery-grid">
      <article><span>01 / criação completa</span><h3>Texto, design e publicação</h3><p>A Suapage escreve os textos, organiza o conteúdo e cria o site. Você fornece as informações do negócio, identidade existente, fotos disponíveis e materiais reais para validarmos tudo juntos.</p></article>
      <article><span>02 / prazo e aprovação</span><h3>7 a 15 dias de produção</h3><p>Contados em dias corridos após o recebimento das informações e materiais necessários. O tempo aguardando sua resposta ou aprovação pausa a contagem e pode alterar a data de entrega.</p></article>
      <article><span>03 / antes da entrega</span><h3>Até 2 rodadas de revisão</h3><p>Cada rodada reúne sua lista de pequenos ajustes em textos, imagens, cores e posicionamento dos elementos existentes. Mudanças de escopo são orçadas separadamente.</p></article>
      <article><span>04 / depois da entrega</span><h3>30 dias de ajustes gratuitos</h3><p>A partir da entrega aprovada e publicada, você pode solicitar pequenos ajustes no que já foi criado. Novas páginas, seções, funcionalidades ou uma nova direção visual ficam fora desse período de suporte.</p></article>
    </div>
    <div className="running-costs"><div><small>Hospedagem gerenciada</small><strong>R$ 49<span>/mês</span></strong><p>A partir da publicação, para manter o projeto no ar com HTTPS. Alterações de conteúdo são tratadas separadamente. E-mail profissional não incluso.</p></div><div><small>Domínio no seu nome</small><strong>Pago por você</strong><p>Você compra e renova o endereço com o provedor. A configuração inicial para conectar seu domínio ao site está incluída no projeto.</p></div><div><small>Alterações após 30 dias</small><strong>R$ 120<span>/hora</span></strong><p>Mínimo de 1 hora por solicitação consolidada. Você recebe e aprova o orçamento antes da execução. Sem mensalidade obrigatória de alterações.</p></div></div>
    <p className="offer-caption">SEO inicial inclui títulos e descrições por página, organização de títulos, endereços legíveis, textos alternativos em imagens pertinentes e configuração de sitemap e indexação quando aplicável. Também otimizamos imagens e carregamento, com verificação em celular e computador. Posição no Google, volume de visitas e notas fixas de desempenho não são garantidos.</p>
  </section>;
}
const questions = [
  ["Preciso entregar os textos prontos?", "Não. A Suapage escreve os textos a partir das informações do seu negócio. Você valida nomes, serviços, preços, credenciais e demais fatos. Fotos próprias, identidade existente e depoimentos reais devem ser enviados por você; não criamos relatos ou resultados fictícios."],
  ["O que conta como uma revisão?", "Uma rodada é uma lista consolidada de ajustes sobre a versão apresentada. São até duas rodadas antes da aprovação final, para refinar textos, imagens, cores e posição de elementos existentes. Uma nova página, nova seção, nova funcionalidade ou mudança completa de conceito requer outro orçamento. Rodadas não utilizadas não viram crédito futuro."],
  ["O que posso pedir nos 30 dias de suporte?", "Trocar um texto ou imagem, atualizar um contato ou preço, ajustar uma cor ou a posição de um elemento existente, além de correções de funcionamento do que foi entregue. O prazo é de 30 dias corridos contados a partir da entrega aprovada e publicada. Solicitações dentro do escopo recebidas nesse prazo permanecem cobertas, mesmo se concluídas depois. Não inclui redesenho, novas seções, páginas ou funcionalidades."],
  ["E depois dos 30 dias?", "Alterações de conteúdo são cobradas sob demanda a R$ 120 por hora, com mínimo de uma hora por solicitação consolidada. Você pode reunir vários pequenos ajustes no mesmo pedido e aprova a estimativa antes do início. Novos escopos são orçados à parte. Eventuais falhas da entrega original são avaliadas separadamente de novas solicitações de conteúdo."],
  ["Posso editar o site ou a Bio por conta própria?", "Nestes pacotes, as alterações são feitas pela Suapage. Você não precisa aprender a usar um editor. Um painel para editar por conta própria, se necessário, é um projeto adicional e não está incluído."],
  ["Hospedagem e domínio são a mesma coisa?", "Não. O domínio é o endereço, comprado e renovado por você no seu nome. A hospedagem mantém o site disponível e custa R$ 49 por mês, a partir da publicação. No combo, o site e a Bio no mesmo domínio usam a mesma hospedagem. E-mail profissional e licenças externas não estão incluídos."],
  ["A hospedagem inclui manutenção de conteúdo?", "Não. A hospedagem cobre a operação para manter o projeto no ar, com HTTPS. Você recebe os 30 dias iniciais de pequenos ajustes; depois, as mudanças são cobradas conforme a solicitação. Limites de infraestrutura e condições de migração são definidos na proposta conforme o projeto."],
  ["O site terá SEO e carregamento otimizado?", "Sim. Incluímos a configuração inicial de SEO e boas práticas de carregamento. Isso prepara o conteúdo para ser compreendido pelos mecanismos de busca. Não inclui produção contínua de conteúdo, anúncios, campanhas de SEO ou promessa de posição no Google. Imagens, vídeos e ferramentas externas influenciam o desempenho."],
  ["O que não entra nos pacotes?", "Criação de identidade visual do zero, ensaio fotográfico, produção de vídeo, tradução, loja virtual, área de membros, painel de edição, automações, sistemas e integrações personalizadas. Na página de produto, conectamos os botões ao checkout externo fornecido por você; a plataforma, taxas, pagamentos e entrega do produto são geridos por ela. Páginas legais, quando necessárias, são orçadas e publicadas a partir de textos fornecidos pelo cliente."],
  ["Como funciona o combo com a Bio?", "Você adiciona uma Bio personalizada por R$ 490 ao contratar o site ou a landing page. É uma página extra, com até seis blocos, mesma identidade visual e até dez links ou botões. Ela usa o mesmo domínio, em um endereço como /bio, e as mesmas condições de revisão e suporte. Não inclui chatbot, carrinho, sistema de agendamento ou editor próprio."],
];
export function OfferFAQ() {
 return <section className="offer-faq shell" id="duvidas"><div><div className="overline">antes de começar</div><h2>Respostas claras.<br /><em>Decisão tranquila.</em></h2></div><div>{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>;
}
