"use client";

import { useState } from "react";

const solutions = [
  { id: "empresa", eyebrow: "Para apresentar", title: "Site Institucional", description: "Sua empresa organizada, valorizada e pronta para ser encontrada.", detail: "Ideal para empresas, clínicas, escritórios e profissionais que precisam construir confiança.", icon: "✦", color: "violet" },
  { id: "servico", eyebrow: "Para vender", title: "Landing Page de Serviço", description: "Uma página pensada para transformar atenção em conversas.", detail: "Ideal para nutricionistas, consultores, personal trainers e prestadores de serviço.", icon: "↗", color: "mint" },
  { id: "produto", eyebrow: "Para lançar", title: "Landing Page de Produto", description: "Sua oferta explicada com clareza até o próximo clique.", detail: "Ideal para e-books, cursos, livros, mentorias e outros produtos digitais.", icon: "◈", color: "peach" },
  { id: "bio", eyebrow: "Para o Instagram", title: "Bio Suapage", description: "O link da sua bio com a estética e a estratégia da sua marca.", detail: "Botões, serviços, produtos e contatos em uma experiência feita para o celular.", icon: "◎", color: "blue" },
];

const packages = [
  { name: "Landing de Serviço", note: "Para transformar visitas em contatos", price: "a partir de R$ 1.800", accent: "mint", items: ["Oferta clara e persuasiva", "Design responsivo", "WhatsApp e formulário"] },
  { name: "Landing de Produto", note: "Para vender um produto digital", price: "a partir de R$ 2.200", accent: "violet", items: ["Estrutura de conversão", "Apresentação da oferta", "Botão para compra"] },
  { name: "Site Institucional", note: "Para apresentar sua empresa", price: "a partir de R$ 3.500", accent: "blue", items: ["Páginas sob medida", "Serviços, equipe e contato", "SEO e alta performance"] },
];

const examples = [
  { tag: "serviço", name: "Clínica Aurora", title: "Cuidar de você começa agora.", desc: "Landing page para uma clínica de nutrição e bem-estar.", accent: "aurora" },
  { tag: "produto digital", name: "Método Essencial", title: "Uma rotina possível para uma vida mais leve.", desc: "Página de vendas para um programa online de organização.", accent: "essential" },
  { tag: "serviço", name: "Estúdio Norte", title: "Arquitetura que traduz o seu jeito de viver.", desc: "Landing page para um escritório de arquitetura autoral.", accent: "north" },
];

export default function Home() {
  const [selected, setSelected] = useState("empresa");
  const [showForm, setShowForm] = useState(false);
  const chosen = solutions.find((item) => item.id === selected) ?? solutions[0];

  return (
    <main>
      <nav className="nav shell"><a className="brand" href="#top" aria-label="Suapage início"><span className="brand-mark">S</span><span>suapage<span className="brand-dot">.</span></span></a><div className="nav-links"><a href="#solucoes">Sites & LPs</a><a href="#pacotes">Soluções</a><a href="#exemplos">Exemplos</a><a href="#processo">Como funciona</a><a href="#bio">Suapage Bio</a></div><button className="nav-cta" onClick={() => setShowForm(true)}>Pedir orçamento <span>↗</span></button></nav>
      <section className="hero shell" id="top"><div className="hero-copy"><div className="kicker"><span className="pulse" /> presença digital com intenção</div><h1>Seu próximo cliente<br /><em>começa aqui.</em></h1><p className="hero-lead">Criamos sites e experiências digitais que fazem sua marca ser percebida, entendida e escolhida.</p><div className="hero-actions"><a className="button button-primary" href="#solucoes">Encontrar minha solução <span>↗</span></a><a className="text-link" href="#processo">Conhecer a Suapage <span>↓</span></a></div><div className="hero-proof"><span className="proof-line" /><span>Design estratégico</span><span>·</span><span>Performance</span><span>·</span><span>Conversão</span></div></div><div className="hero-visual" aria-label="Composição visual representando uma presença digital em evolução"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="visual-card card-back"><div className="browser-chrome" aria-hidden="true"><i className="browser-close">×</i><i className="browser-minimize">−</i><i className="browser-maximize">+</i><small>suapage.com</small></div><span>presença</span><strong>que<br />se nota</strong></div><div className="visual-card card-front"><div className="browser-chrome" aria-hidden="true"><i className="browser-close">×</i><i className="browser-minimize">−</i><i className="browser-maximize">+</i><small>suapage.com</small></div><div className="screen-title">sua marca<br /><b>em movimento.</b></div><div className="screen-button">começar agora <span>→</span></div></div><div className="floating-note note-top">01 <span>clareza</span></div><div className="floating-note note-bottom">02 <span>conexão</span></div></div></section>
      <section className="choice-section" id="solucoes"><div className="shell"><div className="section-intro"><div><div className="overline">comece pelo seu objetivo</div><h2>O que você precisa<br /><em>colocar no mundo?</em></h2></div><p>Não sabe qual formato escolher? Tudo bem. Conte o que você quer alcançar e a gente indica o caminho.</p></div><div className="solution-layout"><div className="solution-list">{solutions.map((item) => <button key={item.id} className={`solution-option ${selected === item.id ? "active" : ""}`} onClick={() => setSelected(item.id)}><span className={`option-icon ${item.color}`}>{item.icon}</span><span><small>{item.eyebrow}</small><strong>{item.title}</strong></span><span className="option-arrow">↗</span></button>)}</div><div className={`recommendation ${chosen.color}`}><div className="recommendation-top"><span className="recommendation-label">a gente recomenda</span><span className="recommendation-number">0{solutions.findIndex((item) => item.id === selected) + 1}</span></div><div className="recommendation-icon">{chosen.icon}</div><h3>{chosen.title}</h3><p>{chosen.detail}</p><a href="#orcamento" onClick={() => setShowForm(true)} className="recommendation-link">Quero conversar sobre isso <span>↗</span></a></div></div></div></section>
      <section className="statement shell"><div className="statement-number">/01</div><div><div className="overline">mais do que um site</div><h2>Uma presença digital<br /><em>à altura da sua ambição.</em></h2></div><p>Seu site é a primeira conversa que muitas pessoas têm com a sua marca. A Suapage transforma essa conversa em percepção de valor.</p></section>
      <section className="bio-section bio-secondary" id="bio"><div className="shell bio-grid"><div className="bio-copy"><div className="overline">um adicional Suapage</div><h2>E quando o Instagram também precisa<br /><em>vender melhor?</em></h2><p>A <b>Suapage Bio</b> é uma extensão opcional para transformar o link do Instagram em uma experiência alinhada ao seu site, serviço ou produto.</p><div className="bio-points"><div><span>01</span><b>Conectada ao seu projeto</b><small>Uma rota clara entre o Instagram e a sua principal oferta.</small></div><div><span>02</span><b>Feita para o celular</b><small>Botões, serviços e contatos em uma experiência simples.</small></div><div><span>03</span><b>Do seu jeito</b><small>Cores e estética da sua marca, sem parecer um link genérico.</small></div></div><a className="button button-light" href="/suapage-bio">Conhecer a Suapage Bio <span>↗</span></a></div><div className="phone-wrap"><div className="phone-glow" /><div className="phone"><div className="phone-notch" /><div className="phone-profile"><div className="avatar">S</div><b>seunegocio</b><span>nutrição que cabe na sua rotina</span></div><div className="phone-links"><div>Agende sua consulta <b>↗</b></div><div>Conheça meu trabalho <b>↗</b></div><div>Fale comigo no WhatsApp <b>↗</b></div></div><div className="phone-social">◎　◉　◌</div><small className="powered">feito com <b>suapage.</b></small></div></div></div></section>
      <section className="packages shell" id="pacotes"><div className="section-intro compact"><div><div className="overline">soluções principais</div><h2>Comece pelo que<br /><em>você quer alcançar.</em></h2></div><p>Sites para apresentar. Landing pages para vender. Uma estrutura clara para cada objetivo.</p></div><div className="package-grid">{packages.map((pack, index) => <article className={`package-card ${index === 0 ? "featured" : ""}`} key={pack.name}><div className="package-head"><span className={`package-dot ${pack.accent}`} />{index === 0 && <span className="popular">mais escolhido</span>}</div><small>{pack.note}</small><h3>{pack.name}</h3><div className="package-price">{pack.price}</div><ul>{pack.items.map((item) => <li key={item}><span>+</span>{item}</li>)}</ul><a href="#orcamento" onClick={() => setShowForm(true)} className="package-link">Ver se é para mim <span>↗</span></a></article>)}</div></section>
      <section className="examples-section" id="exemplos"><div className="shell"><div className="section-intro compact"><div><div className="overline">ideias que ganham forma</div><h2>Alguns caminhos<br /><em>que podemos criar.</em></h2></div><p>Exemplos fictícios para você visualizar como uma página pode traduzir diferentes negócios, públicos e objetivos.</p></div><div className="examples-grid">{examples.map((example, index) => <article className={`example-card ${example.accent}`} key={example.name}><div className="example-browser"><div className="example-top"><span className="example-dots">● ● ●</span><span>suapage / exemplo 0{index + 1}</span></div><div className="example-content"><small>{example.tag}</small><h3>{example.title}</h3><p>{example.desc}</p><div className="example-cta">conhecer <span>↗</span></div><div className="example-blocks"><i /><i /><i /></div></div></div><div className="example-caption"><span>{example.name}</span><span>landing page <b>↗</b></span></div></article>)}</div><div className="examples-note"><span>✦</span> Cada projeto nasce de uma estratégia própria — o exemplo é só o começo da conversa.</div></div></section>
      <section className="process-section" id="processo"><div className="shell"><div className="overline">sem complicação</div><h2>Da primeira ideia<br /><em>ao site no ar.</em></h2><div className="process-grid"><div><span>01</span><h3>Você conta</h3><p>Entendemos seu momento, público e objetivo.</p></div><div><span>02</span><h3>A gente traduz</h3><p>Transformamos sua visão em estrutura e direção.</p></div><div><span>03</span><h3>Você valida</h3><p>Acompanhamos o projeto até ele ficar com a sua cara.</p></div><div><span>04</span><h3>O mundo conhece</h3><p>Publicamos sua presença e deixamos tudo pronto para crescer.</p></div></div></div></section>
      <section className="final-cta shell" id="orcamento"><div className="final-orb" /><div className="overline">o próximo passo é simples</div><h2>Pronto para ser<br /><em>mais percebido?</em></h2><p>Conte para a gente o que você quer construir. A primeira conversa é sem compromisso.</p><button className="button button-primary" onClick={() => setShowForm(true)}>Quero começar meu projeto <span>↗</span></button></section>
      <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span>suapage<span className="brand-dot">.</span></span></a><span>sites & experiências digitais</span><span>© 2026 Suapage</span></footer>
      {showForm && <div className="modal-backdrop" onClick={() => setShowForm(false)}><div className="modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setShowForm(false)} aria-label="Fechar formulário">×</button><div className="overline">vamos conversar</div><h2>Qual é o seu<br /><em>próximo passo?</em></h2><p>Preencha rapidinho. A Suapage responde com uma direção inicial para o seu projeto.</p><form onSubmit={(event) => event.preventDefault()}><label>Seu nome<input placeholder="Como podemos chamar você?" /></label><label>O que você quer criar?<select defaultValue=""><option value="" disabled>Escolha uma solução</option>{solutions.map((item) => <option key={item.id}>{item.title}</option>)}</select></label><label>WhatsApp<input placeholder="(00) 00000-0000" /></label><button className="button button-primary" type="submit">Solicitar orçamento <span>↗</span></button></form></div></div>}
    </main>
  );
}
