"use client";

import { useState } from "react";
import { QuoteDialog } from "./quote-dialog";
import offerData from "./offer-data.json";
import { OfferConditions, OfferFAQ } from "./offer-details";

const solutions = [
  { id: "servico", eyebrow: "Para vender", title: "Landing Page de Serviço", description: "Uma página pensada para transformar atenção em conversas.", detail: "Ideal para nutricionistas, consultores, personal trainers e prestadores de serviço.", icon: "↗", color: "mint" },
  { id: "empresa", eyebrow: "Para apresentar", title: "Site Institucional", description: "Sua empresa organizada, valorizada e pronta para ser encontrada.", detail: "Ideal para empresas, clínicas, escritórios e profissionais que precisam construir confiança.", icon: "✦", color: "violet" },
  { id: "produto", eyebrow: "Para lançar", title: "Landing Page de Produto", description: "Sua oferta explicada com clareza até o próximo clique.", detail: "Ideal para e-books, cursos, livros, mentorias e outros produtos digitais.", icon: "◈", color: "peach" },
];

const packages = Object.values(offerData);
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });



export default function Home() {
  const [selected, setSelected] = useState("servico");
  const [showForm, setShowForm] = useState(false);
  const [requestedSolution, setRequestedSolution] = useState("Landing de Serviço");
  const chosen = solutions.find((item) => item.id === selected) ?? solutions[0];

  return (
    <main>
      <nav className="nav shell"><a className="brand" href="#top" aria-label="Suapage início"><span className="brand-mark">S</span><span>suapage<span className="brand-dot">.</span></span></a><div className="nav-links"><a href="#pacotes">Sites & páginas</a><a href="#entrega">O que está incluído</a><a href="#processo">Como funciona</a><a href="#bio">Site + Bio</a></div><button className="nav-cta" onClick={() => setShowForm(true)}>Pedir orçamento <span>↗</span></button></nav>
      <section className="hero shell" id="top"><div className="hero-copy"><div className="kicker"><span className="pulse" /> sites para quem vive do próprio trabalho</div><h1>Seu próximo cliente<br /><em>começa aqui.</em></h1><p className="hero-lead">Seu serviço bem explicado, sua marca valorizada e um caminho simples até o pedido de orçamento. Nós escrevemos os textos, criamos o design e entregamos tudo pronto para você validar.</p><div className="hero-actions"><a className="button button-primary" href="#pacotes">Ver a página para meu serviço <span>↗</span></a><a className="text-link" href="#processo">Como funciona <span>↓</span></a></div><div className="hero-proof"><span className="proof-line" /><span>Textos + design</span><span>·</span><span>2 revisões</span><span>·</span><span>30 dias de suporte</span></div></div><div className="hero-visual" aria-label="Composição visual representando uma presença digital em evolução"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="visual-card card-back"><div className="browser-chrome" aria-hidden="true"><i className="browser-close">×</i><i className="browser-minimize">−</i><i className="browser-maximize">+</i><small>suapage.com</small></div><span>presença</span><strong>que<br />se nota</strong></div><div className="visual-card card-front"><div className="browser-chrome" aria-hidden="true"><i className="browser-close">×</i><i className="browser-minimize">−</i><i className="browser-maximize">+</i><small>suapage.com</small></div><div className="screen-title">sua marca<br /><b>em movimento.</b></div><div className="screen-button">começar agora <span>→</span></div></div><div className="floating-note note-top">01 <span>clareza</span></div><div className="floating-note note-bottom">02 <span>conexão</span></div></div></section>
<section className="served-sectors shell" aria-label="Áreas atendidas"><p>Já atendemos profissionais de diferentes áreas</p><div><span>Saúde</span><span>Advocacia</span><span>Educação física</span><span>Fotografia</span></div><small>Cada projeto é pensado para o público, os serviços e a identidade de quem atende.</small></section>
      <section className="choice-section" id="solucoes"><div className="shell"><div className="section-intro"><div><div className="overline">comece pelo seu objetivo</div><h2>O que você precisa<br /><em>colocar no mundo?</em></h2></div><p>Não sabe qual formato escolher? Tudo bem. Conte o que você quer alcançar e a gente indica o caminho.</p></div><div className="solution-layout"><div className="solution-list">{solutions.map((item) => <button key={item.id} className={`solution-option ${selected === item.id ? "active" : ""}`} onClick={() => setSelected(item.id)}><span className={`option-icon ${item.color}`}>{item.icon}</span><span><small>{item.eyebrow}</small><strong>{item.title}</strong></span><span className="option-arrow">↗</span></button>)}</div><div className={`recommendation ${chosen.color}`}><div className="recommendation-top"><span className="recommendation-label">a gente recomenda</span><span className="recommendation-number">0{solutions.findIndex((item) => item.id === selected) + 1}</span></div><div className="recommendation-icon">{chosen.icon}</div><h3>{chosen.title}</h3><p>{chosen.detail}</p><a href="#orcamento" onClick={() => { setRequestedSolution(selected === "produto" ? "Landing de Produto" : selected === "empresa" ? "Site Institucional" : "Landing de Serviço"); setShowForm(true); }} className="recommendation-link">Quero conversar sobre isso <span>↗</span></a></div></div></div></section>
      <section className="statement shell"><div className="statement-number">/01</div><div><div className="overline">mais do que um site</div><h2>Uma presença digital<br /><em>à altura da sua ambição.</em></h2></div><p>Seu site é a primeira conversa que muitas pessoas têm com a sua marca. A Suapage transforma essa conversa em percepção de valor.</p></section>

      <section className="packages shell offer-packages" id="pacotes"><div className="section-intro compact"><div><div className="overline">criação completa, do texto à publicação</div><h2>Você cuida do negócio.<br /><em>A gente cuida da página.</em></h2></div><p>Comece pelo seu objetivo. Todos os projetos incluem textos, design, desenvolvimento, publicação e duas rodadas de revisão.</p></div><div className="package-grid">{packages.map((pack, index) => <article className={`package-card ${index === 0 ? "featured" : ""}`} key={pack.id}><div className="package-head"><span className={`package-dot ${pack.accent}`} />{index === 0 && <span className="popular">para vender seu serviço</span>}</div><small>{pack.note}</small><h3>{pack.name}</h3><div className="package-price"><small>a partir de</small>{money(pack.price)}</div><p className="offer-limit">{pack.limit}</p><ul>{pack.items.map(item => <li key={item}><span>+</span>{item}</li>)}</ul><details className="offer-structure"><summary>Veja a estrutura sugerida</summary><ol>{pack.sections.map(item => <li key={item}>{item}</li>)}</ol></details><p className="offer-mini-terms">7 a 15 dias de produção · 2 revisões<br />30 dias de pequenos ajustes após a entrega</p><a href="#orcamento" onClick={() => { setRequestedSolution(pack.name); setShowForm(true); }} className="package-link">{index === 0 ? "Quero uma página para meu serviço" : "Conversar sobre este projeto"}<span>↗</span></a></article>)}</div><p className="offer-caption">Seção é um bloco de conteúdo dentro de uma página. A estrutura é adaptada ao seu negócio dentro do limite contratado. Hospedagem, domínio e opcionais são apresentados separadamente na proposta.</p></section>
      <OfferConditions />

      <section className="process-section" id="processo"><div className="shell"><div className="overline">sem complicação</div><h2>Da primeira ideia<br /><em>ao site no ar.</em></h2><div className="process-grid"><div><span>01</span><h3>Você conta</h3><p>Entendemos seu momento, público e objetivo.</p></div><div><span>02</span><h3>A gente traduz</h3><p>Escrevemos os textos e criamos o design com base no seu negócio.</p></div><div><span>03</span><h3>Você valida</h3><p>Você recebe a página pronta e pode reunir seus ajustes em até duas rodadas de revisão.</p></div><div><span>04</span><h3>O mundo conhece</h3><p>Após sua aprovação, publicamos e iniciamos os 30 dias de pequenos ajustes gratuitos.</p></div></div></div></section>
      <section className="bio-section bio-secondary" id="bio"><div className="shell bio-grid"><div className="bio-copy"><div className="overline">um adicional Suapage</div><h2>Seu site e sua Bio.<br /><em>A mesma identidade.</em></h2><p>Adicione ao seu projeto uma <b>Bio personalizada</b>, com as mesmas cores, tipografia e direção visual do site. Quem chega pelo Instagram encontra seus serviços e os próximos passos em um só link.</p><div className="bio-points"><div><span>01</span><b>Conectada ao seu projeto</b><small>Uma rota clara entre o Instagram e a sua principal oferta.</small></div><div><span>02</span><b>Feita para o celular</b><small>Botões, serviços e contatos em uma experiência simples.</small></div><div><span>03</span><b>Do seu jeito</b><small>Cores e estética da sua marca, sem parecer um link genérico.</small></div></div><p className="bio-combo-price">Adicione ao seu projeto por <b>R$ 490</b></p><p className="bio-combo-limit">Até 6 blocos e 10 links. Mesma identidade, mesmo domínio e uma só hospedagem.</p><a className="button button-light" href="/suapage-bio">Conhecer o combo Site + Bio <span>↗</span></a></div><div className="phone-wrap"><div className="phone-glow" /><div className="phone"><div className="phone-notch" /><div className="phone-profile"><div className="avatar">S</div><b>seunegocio</b><span>Seu trabalho, bem apresentado.</span></div><div className="phone-links"><div>Conheça meus serviços <b>↗</b></div><div>Conheça meu trabalho <b>↗</b></div><div>Fale comigo no WhatsApp <b>↗</b></div></div><div className="phone-social">◎ ◉ ◌</div><small className="powered">feito com <b>suapage.</b></small></div></div></div></section>
      <OfferFAQ />
      <section className="final-cta shell" id="orcamento"><div className="final-orb" /><div className="overline">o próximo passo é simples</div><h2>Vamos colocar seu serviço<br /><em>no lugar certo?</em></h2><p>Conte o que você oferece e para quem. Nós indicamos o formato e enviamos uma proposta com escopo, prazo e custos definidos.</p><button className="button button-primary" onClick={() => setShowForm(true)}>Quero começar meu projeto <span>↗</span></button></section>
      <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span>suapage<span className="brand-dot">.</span></span></a><span>sites & experiências digitais</span><span>© 2026 Suapage</span></footer>
      {showForm && <QuoteDialog initialSolution={requestedSolution} onClose={() => setShowForm(false)} />}
    </main>
  );
}
